# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Delly Sartika
tagline:          GitHub Site
description:      Games & Other Stuff
url:              https://sartikadelly.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sartikadelly/sartikadelly.github.io
